steps:
  # Build OpenClaw gateway image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/openclaw-gateway:${_SHORT_SHA}"
      - "-t"
      - "gcr.io/${PROJECT_ID}/openclaw-gateway:latest"
      - "."

  # Build mock API image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/vrm-mock-api:${_SHORT_SHA}"
      - "-t"
      - "gcr.io/${PROJECT_ID}/vrm-mock-api:latest"
      - "./mock-api"

images:
  - "gcr.io/${PROJECT_ID}/openclaw-gateway:${_SHORT_SHA}"
  - "gcr.io/${PROJECT_ID}/openclaw-gateway:latest"
  - "gcr.io/${PROJECT_ID}/vrm-mock-api:${_SHORT_SHA}"
  - "gcr.io/${PROJECT_ID}/vrm-mock-api:latest"

substitutions:
  _SHORT_SHA: "latest"

options:
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
