#!/bin/bash
# Fetch secrets from GCP Secret Manager and write .env file.
# Usage: ./deploy/fetch-secrets.sh [project-id]
set -euo pipefail

PROJECT_ID="${1:-jarvis-ml-dev}"
ENV_FILE="/opt/openclaw/.env"

fetch() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT_ID" 2>/dev/null \
    || { echo "ERROR: failed to fetch secret '$1'" >&2; exit 1; }
}

echo "Fetching secrets from project=$PROJECT_ID ..."

cat > "$ENV_FILE" <<EOF
# Auto-generated by fetch-secrets.sh — do not edit manually
GCP_PROJECT_ID=$PROJECT_ID
OPENCLAW_GATEWAY_TOKEN=$(fetch openclaw-gateway-token)
GOOGLE_API_KEY=$(fetch openclaw-google-api-key)
MODEL_PRIMARY=google/gemini-3-flash-preview
SLACK_BOT_TOKEN=$(fetch openclaw-slack-bot-token)
SLACK_APP_TOKEN=$(fetch openclaw-slack-app-token)
VRM_ADMIN_API_KEY=$(fetch openclaw-vrm-admin-api-key)
VRM_ADMIN_API_URL=http://mock-api:3001
JARVIS_URL=https://jarvis-dot-jarvis-ml-dev.uc.r.appspot.com
JARVIS_API_KEY=$(fetch openclaw-jarvis-api-key)
MCP_MINER_URL=https://miner-dot-jarvis-ml-dev.uc.r.appspot.com/mcp/
MCP_MINER_API_KEY=$(fetch MINER_MCP_API_KEY)
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
